# Chargement des librairies

library(shiny)
library(markdown)
library(shinythemes)
library(reshape2)
library(ROCR)
library(class)
library(dplyr)
library(readxl)
library(ROCR)
library(pROC)
library(class)
library(magrittr)
library(factoextra)
library(ggbiplot)
library(ggplot2)
library(plotly)
library(bslib)
library(plyr)
library(readr)
library(caret)
library(glmnet)

# Using custom shiny theme
thematic::thematic_shiny(font = "auto")